flaskr/__init__.py
import os

from functools import wraps
from flask import Flask, render_template, redirect, flash, url_for, current_app, request
from flask_sqlalchemy import SQLAlchemy
from flaskr.config import Config

db = SQLAlchemy()

def create_app(config_class=Config):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(Config)
    db.init_app(app)

    from .views import views
    from .api import api
    
    @app.errorhandler(404)
    def not_found(e):
        return render_template("404.html"), 404

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(api, url_prefix="/api")

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    return app

flaskr/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from . import db

views = Blueprint("views", __name__)


@views.route("/")
def index():
    return render_template(
        "page/index.html",
        page="home",
    )

@views.route("/home")
def home():
    return render_template(
        "page/index.html",
        page="home",
    )

@views.route("/pelatihan")
def pelatihan():
    return render_template(
        "page/pelatihan.html",
        page="pelatihan",
    )

@views.route("/prediksi")
def prediksi():
    return render_template(
        "page/prediksi.html",
        page="prediksi",
    )

flaskr/templates/layout/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CNN Sawit</title>
  <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/png">
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='dt/datatables.min.css')}}" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/materialize.min.css')}}" />
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
    integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css')}}" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/pages/dashboard.css')}}" />
  {% block style %}{% endblock %}
</head>

<body>

  <div class="frame">
    <div class="nav-wrapper">
      <a class="nav-link" href="{{ url_for('views.home') }}" data-page="home">Dataset</a>
      <a class="nav-link" href="{{ url_for('views.pelatihan') }}" data-page="pelatihan">Pelatihan</a>
      <a class="nav-link" href="{{ url_for('views.prediksi') }}" data-page="prediksi">Identifikasi</a>
    </div>
    <div class="content-wrapper">
      {% block inside %}{% endblock %}
    </div>
  </div>
  <script src="{{ url_for('static', filename='js/jquery-3.7.1.min.js')}}"></script>
  <script src="{{ url_for('static', filename='js/chart.umd.js')}}"></script>
  <script src="{{ url_for('static', filename='js/swal.js')}}"></script>
  <script src="{{ url_for('static', filename='dt/datatables.min.js')}}"></script>
  <script src="{{ url_for('static', filename='js/materialize.min.js')}}"></script>
  <script src="{{ url_for('static', filename='js/utils/puller.js')}}"></script>
  <script>
    let page = "{{ page }}";
    const cloud = new Puller();
  </script>
  <script src="{{ url_for('static', filename='js/main.js')}}"></script>
  {% block script %}{% endblock %}
</body>

</html>

flaskr/templates/page/index.html
{% extends "layout/dashboard.html" %}
{% block inside %}
<div class="page-wrapper" id="dataset">
  <p class="center">Am</p>
</div>
{% endblock %}
{% block script %}
<script src="{{ url_for('static', filename='js/pages/home.js')}}"></script>
{% endblock %}

flaskr/templates/page/pelatihan.html
{% extends "layout/dashboard.html" %}
{% block inside %}
<div class="page-wrapper">
  <div class="container">
    <form class="row" method="post" id="form-pelatihan">
      <div class="col s8 input-field">
        <input id="input-pelatihan" name="name" type="text" class="validate">
        <label for="input-pelatihan">Nama Model</label>
      </div>
      <div class="col s4 center input-field">
        <button class="waves-effect waves-light btn" id="btn-pelatihan" type="submit">Tambah</button>
      </div>
    </form>
    <div class="row" style="display: none;" id="loader-pelatihan">
      <div class="col s12">
        <p class="center">Melatih Model</p>
      </div>
      <div class="col s12">
        <div class="progress">
          <div class="indeterminate"></div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <table id="table-pelatihan"></table>
      </div>
    </div>
  </div>
</div>
<!-- Modal Structure -->
<div id="accuracyModal" class="modal modal-fixed-footer">
  <div class="modal-content">

    <img id="accuracyImage" src="" alt="Accuracy Plot" style="width: 100%; height: auto;">
  </div>
  <div class="modal-footer" style="display: flex; justify-content: space-between; align-items: center;">
    <p style="margin: 0;">Accuracy Plot</p>
    <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
  </div>

</div>

{% endblock %}
{% block script %}
<script src="{{ url_for('static', filename='js/pages/pelatihan.js')}}"></script>
{% endblock %}

flaskr/templates/page/prediksi.html
{% extends "layout/dashboard.html" %}
{% block inside %}
<div class="page-wrapper">
  <div class="row">
    <div class="col s12 m6 offset-m3">
      <form action="" class="row" method="post" id="form-prediksi">
        <div class="col s12 input-field">
          <select name="name" id="name">
            <option value="" disabled selected>Pilih Model</option>
          </select>
        </div>
        <div class="col s12 file-field input-field">
          <div class="btn">
            <span>Gambar</span>
            <input type="file" id="image" name="image" accept="image/*">
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
          </div>
        </div>
        <div class="col s12 center input-field">
          <button class="waves-effect waves-light btn" id="btn-prediksi" type="submit">identifikasi</button>
        </div>
      </form>
      <div class="row" style="display: none;" id="loader-prediksi">
        <div class="col s12">
          <p class="center">Melakukan identifikasi</p>
        </div>
        <div class="col s12">
          <div class="progress">
            <div class="indeterminate"></div>
          </div>
        </div>
      </div>
      <p class="center" id="hasil" style="font-weight: bold; font-size: 1.5rem;">
        Hasil identifikasi
      </p>
      <div class="row">
        <div class="s12">
          <table id="table-prediksi">
            <thead>
              <tr>
                <th>Kelas</th>
                <th>Nilai</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="page-wrapper page-slider">
  <h1>Page 2</h1>
  <h1>0</h1>
</div>
{% endblock %}
{% block script %}
<script src="{{ url_for('static', filename='js/pages/prediksi.js')}}"></script>
{% endblock %}